[package]
name = "to_do"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.159", features = ["derive"] }
serde_json = "1.0.96"
clap = { version = "4.5", features = ["derive"] }

[dev-dependencies]
tempfile = "3"