name: CI Workflow
description: This workflow runs unitary and integration tests and coverage checks on pull requests to the main branch.

on:
    pull_request:
        branches:
            - main

jobs:
    test:
        name: Run unitary tests
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install Rust
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  override: true

            - name: Install cargo-tarpaulin
              run: cargo install cargo-tarpaulin

            - name: Run unit tests + integration tests + coverage output 
              run: cargo tarpaulin --tests --all-features --out Xml --output-dir coverage --line --fail-under 80 --include-tests -- --test-threads=1

            - name: Verify coverage report exists
              run: |
                test -f coverage/cobertura.xml
                head -n 20 coverage/cobertura.xml

            - name: Upload coverage reports to Codecov
              uses: codecov/codecov-action@v5
              with:
                files: coverage/cobertura.xml
                token: ${{ secrets.CODECOV_TOKEN }}
                flags: rust
                fail_ci_if_error: true
