name: Unitary tests check for ToDo app

on:
    pull_request:
        branches:
            - main

jobs:
    test:
        name: Run unitary tests
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install Rust
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  override: true

            - name: Cache Cargo dependencies
              uses: actions/cache@v3
              with:
                  path: |
                      ~/.cargo/registry
                      ~/.cargo/git
                      target
                  key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-cargo-

            - name: Install cargo-tarpaulin
              run: cargo install cargo-tarpaulin

            - name: Test with cargo
              run: cargo test --verbose -- --nocapture
              
            - name: Run coverage
              run: cargo tarpaulin --out Html --output-dir coverage --line --fail-under 80
            
            - name: Upload coverage report
              uses: actions/upload-artifact@v4
              with:
                name: coverage report
                path: coverage/test_coverage.html
